davmail.ssl.keystoreType=
davmail.ssl.keystorePass=
davmail.proxyPassword=
davmail.oauth.tenantId=
davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c
davmail.smtpPort=1025
davmail.enableKerberos=false
davmail.folderSizeLimit=0
davmail.forceActiveSyncUpdate=false
davmail.imapAutoExpunge=true
davmail.useSystemProxies=false
davmail.proxyUser=
davmail.caldavEditNotifications=false
davmail.ssl.nosecuresmtp=false
davmail.caldavPastDelay=90
davmail.ssl.keyPass=
log4j.logger.httpclient.wire=INFO
davmail.noProxyFor=
davmail.server=true
log4j.logger.org.apache.commons.httpclient=INFO
davmail.popMarkReadOnRetr=false
davmail.ssl.nosecureimap=false
davmail.disableTrayActivitySwitch=false
davmail.caldavAutoSchedule=true
davmail.enableProxy=false
davmail.proxyPort=
davmail.logFileSize=1MB
davmail.oauthpersistToken=true
davmail.mode=O365Modern
davmail.smtpSaveInSent=true
davmail.bindAddress=
davmail.ssl.nosecurepop=false
davmail.ssl.pkcs11Library=
log4j.rootLogger=INFO
davmail.ssl.keystoreFile=
davmail.oauth.jds6696@psu.edu.refreshToken={AES}L1/9rO1BHnoeDyVDhWk4jzUShK+XHuX0XySntnIEMQrlOCLoRMfvDkxOmO5GK3wyP3V+hDL6A8wNEXD9pSbr3ppUJ5JSxvx/fWRy6/+A4waNGoIlwF4Zre9m5G6NQqHGNi7hDneIarsqb8x5UdYK95ADVOLuOaLjI4GN5gUhxjvvrqg+X5ZB96ZPH3ulljFCEJnRiuD/7KDQnXLIZEz+okheSLNEt6EIZ3jDp9mydzk4JR/0dhMJV0Ff+OKSH1x0MSeZEaZz4wEaClpj5FAxK180n0GSGiPu0LSV0F9i56YB0GAtffm71J1FQRjM+DuqaHhdpcOvWL3zksC0eejmzFWgUA0VRwNgOAkhbCsOdnkBGYM0qvOeXKV2Eq2MwksVj7hU8C0Gp3t+YttEOgnMGFkg2Qft68blAKcG065JYQPS/vwXEuYYSK1yN3U/+sxveg1AYhg8UqVYpQJ4r1qB5e5rb0pUH+bx9i8q2DCb7L6N4gJDN4XnmbHQyRwUfl9QYULv3A/CY60WkZfwPhwul5Lt++w8UckDkyGBcQcEKWQ3qlqYg6sS9mCYAkdv8MElcoBL8BLjz/V/JRribR7/0gke5Ui2x2/vqsynZy6S04lmOhefnwbQTK+PYHOb/1DCqsGeY/N8jUktNJcJu+BL3AOfUmaoo5yqjNBVXm7eP+kRUYFgfk5RrT2XL1SkAUeY5uav/KlBmnqdmwZh6PrSw4Um2qIL/NDBH9SGllRhetw001J5KQJTYWNQ7f46Aplp8z4Af5FVD4uyqisYRC/q0S+tY9mgQsr04T4Ci7TMw5Pp4G1P5P9AZke84D04Y2/S7bv2tmrrih+r7FEbSwpy4YDIVk///5iffIaU9x50Q+2Pc/JN9Ch4TbgS9irLAPDKqkvsnZlGFCexnWZGT+jA2IWLDPuVFRjPmYVVwz8/ef7CiKKFb/g3cYc9TrsdnMuk3ixll0g0pLwPHq4ZAd96oUSA8Rby7V5vIEAkH7gUlx/A2HnegCogu37PpInKShK2QcLQotiLXIz9mkYgu/1eVLCQ6AXc6xhOBTsD1dPR/AtO38YXsDiiRM5WjNMghhx+2Y2EVJA66ih8jzZ/valO4AD49bW1vm99tNgDm29Vpud0Z+3v3Yd8fx+TnyOFUtz7vNFJIcMbboTj996+fLUlEeiC/J5ENkf9f1xGsM0ERECERI9Gl94I0alhi5RntmC1NgfS3j9zkeeutEH9SkYlQ0XWCI7NORXS2jjbkpuJrYmzWeV7qBtXIrb+/LIUnN0semKxeklsCpBNcyN5IG2uYDx2mERsq1+x0t2oqKngvKMnIrFAn+ODBm9KVPmgmJLePFluozey0dqd78HhSm6VUQP5R2lEpeISifC+Ot0sO5bH+UO9VK7SKpgPB2sFca/xyVa2ReNQjb+SoaAGxIsGGSM8MIY3/LHE5aRGjgRdiFXZcEBUpHACsxmYJ8Do4Dl/m8Lfeo9aJPGaLEPbUHSEbFNFPhKHFsKVQB8hpr59pYeeS9vY5Cpy+/NDGON3QIPPCIf1YMUcS5yzV8uY7RKNNnTTLxw68d93SkjNO2qVInzv20rdAGtzpHMExkCZZ61KKoFZHt/nO7aiN3ue5dUzaivHL/63BoDohijrQL0JQELvaIvM0FQp5xWBmNhlxgFwfqNb9COzAfcJ86bKk3lc2lwW7pxmclzx8EFUaSIEbFG7zJSqEt1yRci33AAIwrH31MPYnPP7W4WOvENInQ4/sP+72aNg+vN/vDd/DRA1bbqCNeR5EDF1UwLKe46Htr4DHufaCVdmIqA7Anu7DxFeJEaV5yKTupjrn/ED5xhmzFPemywfoA3LznIkfnidbne1Iz1OE7BunaVoM+bLL8GVdaPia5atXcQzGCsA84t8715qGvxVkixC1mnsOR4gGa1tttsAL54o0luziQJ6lwlowLx5g+Oc7dgsRJ4OXD10LJlxzRpf/XVGV3m7dAMZF62Dn4RNy6Wq4+Ume/TtHSAEHA==
log4j.logger.davmail=INFO
davmail.ssl.clientKeystoreType=
davmail.clientSoTimeout=
davmail.ssl.pkcs11Config=
davmail.ssl.clientKeystorePass=
davmail.imapPort=1143
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx
log4j.logger.org.apache.http.conn.ssl=INFO
davmail.sentKeepDelay=90
davmail.ssl.nosecureldap=false
davmail.imapAlwaysApproxMsgSize=false
davmail.ssl.nosecurecaldav=false
davmail.popPort=1110
davmail.defaultDomain=
davmail.showStartupBanner=true
davmail.proxyHost=
davmail.ldapPort=1389
davmail.server.certificate.hash=
log4j.logger.org.apache.http.wire=INFO
davmail.disableGuiNotifications=false
davmail.imapIdleDelay=
davmail.allowRemote=true
davmail.disableUpdateCheck=true
log4j.logger.org.apache.http=INFO
davmail.caldavPort=1080
davmail.enableKeepAlive=true
davmail.ssl.clientKeystoreFile=
davmail.logFilePath=/var/log/davmail.log
davmail.keepDelay=30
davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob
davmail.caldavAlarmSound=
