davmail.ssl.keystoreType=
davmail.ssl.keystorePass=
davmail.proxyPassword=
davmail.oauth.tenantId=
davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c
davmail.smtpPort=1025
davmail.enableKerberos=false
davmail.folderSizeLimit=0
davmail.forceActiveSyncUpdate=false
davmail.imapAutoExpunge=true
davmail.useSystemProxies=false
davmail.proxyUser=
davmail.caldavEditNotifications=false
davmail.ssl.nosecuresmtp=false
davmail.caldavPastDelay=90
davmail.ssl.keyPass=
log4j.logger.httpclient.wire=INFO
davmail.noProxyFor=
davmail.server=true
log4j.logger.org.apache.commons.httpclient=INFO
davmail.popMarkReadOnRetr=false
davmail.ssl.nosecureimap=false
davmail.disableTrayActivitySwitch=false
davmail.caldavAutoSchedule=true
davmail.enableProxy=false
davmail.proxyPort=
davmail.logFileSize=1MB
davmail.oauthpersistToken=true
davmail.mode=O365Modern
davmail.smtpSaveInSent=true
davmail.bindAddress=
davmail.ssl.nosecurepop=false
davmail.ssl.pkcs11Library=
log4j.rootLogger=INFO
davmail.ssl.keystoreFile=
davmail.oauth.jds6696@psu.edu.refreshToken={AES}L1/9rO1BHnoeDyVDhWk4jzUShK+XHuX0XySntnIEMQrlOCLoRMfvDkxOmO5GK3wyP3V+hDL6A8wNEXD9pSbr3ppUJ5JSxvx/fWRy6/+A4waNGoIlwF4Zre9m5G6NQqHG083I5QQ66zGsC70flKEhSNzDp/czIuL/C172UzWnUp4RPADBKWZr46tPXe2Myfeud3JE4JG8wGt2QNYg9bxab3+Hz7BYAHEvTibMedQXPMZHu/UFbdF0PrIe8tiTxgBDdlpT47mCTNNfHmZvoz9tZcUL5o/rWRXdFBPpGfhWAVO2QMEGivlsemDdC6Qn4DuMqwcFUmqyfN67xvjvIO3AaDNAR8R5yfK4Akbw6UnMigywZl4G5+xbkt07buTbWfoZXTHWllcLQuBqWRH9tcbzsoUFqKNUXEuZgcsIrq7emczAhpKHBMK+dKKMjO3Jp8DZ8YoZxjMqVqdrZIc48k/Ka+vZjvKf/74eyHJa82CbwZZ2HXcQLe2ARAikR6HWLLwaGjLuzAsbyXFsW43rgGoVTCqaqgz35kgpw9IkEbCXjB6Ra/9um5t5bef06XqiQbF5lEWj6byAd5G75XNvmeYO5EJtKAvfQWA9HtDuCoClS52qpgq9WJz7r/wBQmm8+ewJTgh4HgFyjg9Z71+GXKbfSHPhMJ8y+v9t4Jvfh+rhkdCPzUZn9Sfb7Z5j+sQy/jVdjZnWOYj3dFcRevmP+rOdTNiM+Pk3w/luPQVmDNHKvHTc619EEz0rvZ2l85W8KhIrz+X7RfmD64FKa1yQ/KMzpnheQ2gTcDMTJAVTUwpw+uNRCZqRS6l5RrW9yRbA2m9W7eS0S7rbmv5IDqJ6qRgCHNTkNNQDwI2SQBB2GyDOlz5CIbXou/UqLRdl3umv6Yo5YPCgWQ/yWDlFqjB1v5ASYDf7MjrJn2GxXxuPYPAtYueDj0TrAYSobZId54H0/ujFnldyQC2VD6+UYDqlhmACL0DXCo5AE9P1K4+iXhGYD+R40J4PVpJlwtzF1umzj0vxKd+EyAUkg3RP8R7ECY2h+ZPxD58R0bneBKSVty5O6RF6yFJvP6iWzI8l+bfY3sO627+sPFuXawbHY50hnjmCW2GIpkovaePSYRpt0JjvxurnStjMQSo+viwrpTsXEAUrFBsgJ2gLuXvfTtLVHy1lava56hEA8Yj9nKeGps0G9yUvBCdSVDOy0cU/O9S3TCXQ7CTNkl/mVV1z+19BPSfA6sJV7jsTNMLxSyZKuc4GvR7EyMUZ6UBJMylLaclFAYwd1nTLCdigUEpmbQV593Vt17JgohQVhmqR3/lpsjpbNbCM+Fz7IYhGQp+z9Muz/L2uXtZwjtZZ8eFar8WNoesriUKkOBMJqyU5cjxIedq1Cj7dzTscOLnQaX0OF7vxTw0OuelmrbtM1zmbqwihefyIP4D6MOgXZwM/PZHQlkVGvewESDxqX4ndWmfFPbuU+Ow14ouR/mWR/PoJXTXR4gi7daFz3+nSR1fXIKdozEXGyOw/GA+zl51lrhx9C+MAJS+YtYny8hphLZBgb43tGZ+A0TJWiJ8aHYL+u8DUtFtM2BDTd51Q9hOLmucB3e3IkMj9QtkoBtJQdHIDNeYHQMlVbhgCOwMBiaO6f042fDcNTby/A7R/gOtjgBSfv1TarxOAN+4tyhZPW5uNkmNwY2+QeFDQVDhvgbcXB0LowYO3liLup3npzuIXT/2cKkTdd7kH7h2pVbHoiER7ucNBFVZEseCXf2JJxI4OuQFeAdEoEhe1S6LU20uFyzaFaHk9FcFUuDOHs/ViZLTbN4uaLclbsCJu9Qw7Xd2caXObYInuvRDNaoVQ2AI3U0sUcJMBMZ8jDv/qGqNLUs3o6fA9OyUhVkJmog6Qt8IwO612VBX4s1SWVyPc67ogpY2Hlrj5ddfmpEkpZ3CiDoJSR+Wdpp4H8FTin3FzUnmpa3KecOL0gvCt5sR2yFw8pUwOb3UIvFmdJA6/bfahNVDpubcmPrgyMenzZ8Qv6xtmylBeNpQBNtw=
log4j.logger.davmail=INFO
davmail.ssl.clientKeystoreType=
davmail.clientSoTimeout=
davmail.ssl.pkcs11Config=
davmail.ssl.clientKeystorePass=
davmail.imapPort=1143
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx
log4j.logger.org.apache.http.conn.ssl=INFO
davmail.sentKeepDelay=90
davmail.ssl.nosecureldap=false
davmail.imapAlwaysApproxMsgSize=false
davmail.ssl.nosecurecaldav=false
davmail.popPort=1110
davmail.defaultDomain=
davmail.showStartupBanner=true
davmail.proxyHost=
davmail.ldapPort=1389
davmail.server.certificate.hash=
log4j.logger.org.apache.http.wire=INFO
davmail.disableGuiNotifications=false
davmail.imapIdleDelay=
davmail.allowRemote=true
davmail.disableUpdateCheck=true
log4j.logger.org.apache.http=INFO
davmail.caldavPort=1080
davmail.enableKeepAlive=true
davmail.ssl.clientKeystoreFile=
davmail.logFilePath=/home/jds6696/.davmail.log
davmail.keepDelay=30
davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob
davmail.caldavAlarmSound=
