davmail.ssl.keystoreType=
davmail.ssl.keystorePass=
davmail.proxyPassword=
davmail.oauth.tenantId=
davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c
davmail.smtpPort=1025
davmail.enableKerberos=false
davmail.folderSizeLimit=0
davmail.forceActiveSyncUpdate=false
davmail.imapAutoExpunge=true
davmail.useSystemProxies=false
davmail.proxyUser=
davmail.caldavEditNotifications=false
davmail.ssl.nosecuresmtp=false
davmail.caldavPastDelay=90
davmail.ssl.keyPass=
log4j.logger.httpclient.wire=INFO
davmail.noProxyFor=
davmail.server=true
log4j.logger.org.apache.commons.httpclient=INFO
davmail.popMarkReadOnRetr=false
davmail.ssl.nosecureimap=false
davmail.disableTrayActivitySwitch=false
davmail.caldavAutoSchedule=true
davmail.enableProxy=false
davmail.proxyPort=
davmail.logFileSize=1MB
davmail.oauthpersistToken=true
davmail.mode=O365Modern
davmail.smtpSaveInSent=true
davmail.bindAddress=
davmail.ssl.nosecurepop=false
davmail.ssl.pkcs11Library=
log4j.rootLogger=INFO
davmail.ssl.keystoreFile=
davmail.oauth.jds6696@psu.edu.refreshToken={AES}L1/9rO1BHnoeDyVDhWk4jzUShK+XHuX0XySntnIEMQrlOCLoRMfvDkxOmO5GK3wyP3V+hDL6A8wNEXD9pSbr3ppUJ5JSxvx/fWRy6/+A4waNGoIlwF4Zre9m5G6NQqHGhmy/tFukv2hf/L4Tb6sZCFq2vxjnVVMRI5ZXULsTaTRNHcMgN2QNJ5GfvPe7V0ASY0TJRKs88kxK9dU7Tj1WHwZ3vCoUrxI5qkKrWVIjGpZMwA4X9Zdedqf9Fev7UvTGpSyKb1fjesZeQDcLvu6kZUZ9k3cGEn7q6mApZz1h4kBl0sZsAUN5ztwb1CAWw8PNgrqyzkrgUFT4MCsvGI0vPjZd/3eGe5JQM19EVmurWA4iTFa+i2wZldoRudQrDEVCBbqF6fPXF8UO1yGZY0FtfgDo6YErhweMgXI8jiWDwgUcnNDwu4fbO604w+NvlrlZh7n3NTbaPTAlESgT2/0CQlOnZM5a3yYGVEsd4237eOSbAljucOFbjU69lqnRyeY0UchOAbbiYWHAJ8i9wIenFSZlQ/qJrtSIUx74QX2JmGmqA3p1k5Ct6fm3Sh2TcgZrXgVYm1SR5TgoWnLskSQEdXaXpJWFqfq4puhBOKD9+OlE2qmT+lxw3unForzqlDgDYjpZfbl8WXLmM36jJtL2itM5PwKUnNk2febQ1BiegHJFxSts4cI8urx7ZFeEEXk/UsNBxPyjF6bYgXdhKKY4ldSv3iqu/nEGhnEgsUpDPXM+KJpbJOvGOT2gVNZ4HNSbt9SEOM0fLgyzywZUjxHgm/zgSgaVktVpPuXRS6aaVcWTrzM1MnoZ14lqntIMlwX2zcnnKVG8lt7lx7aGh9NGp2ZQA9lwTZTcU+W2QnoUFyd0mBqkjvyZ6rt+qx5wKdh+qK3DcuGKjwg/4I0RHNMtahOsSeoGu1L5TGVu9/Dqbw4Is214ART8QFqVw51P14qPBDUnAeLlgkXeFOdb9/DxooawRUEFq5e+JyHvPLNfI9hjS1ctHdMZUACI7XYB3IKw9BL9OV4uyAbMPpbjgmF8pZX1xrzsmCxYG1PgDOwopT7/UR5730E10wfHq2JhYGQqAUm6f/YQvwHT7lCI2VKPB4hazuSApL84+BUi1VbUkXeJ62ZEJ5JemVXmOA4VORQkSEKGzIwABnBVn1+BSahLzzLMjaOC8Ghze0JqalvTu3n9HMticaQ9UrSoScm+nZGDHWENRSR01mYx2mU1RkBPcqfJtRwkRoE099fbRenmx4GylYHPl1ku7ZDhSHHNB1uCsgMMU1l4inWbhk5BdC0TRQxE4Gq+xNJuH7pVOv+6on6B0u/lg9T0MNIx4N8SmF0OQ6R272smyFPnliqAZ4A7BHwyTOtuo8tna/XvpesLNEtzv3tdqvEY2KyRCXcJkyMm6HKrwLPVndJuZT9MCxg7J50pgB8JmJpTe2AS4b36sOJQ7sXq6QKokIp52KNBbIcjC5tGBQ9aF9VR8PARtsRoGGcMBe9srEYMDfAHDfZAWPI9Ng6UG7nwQkyHussyuGQW/Yi1Ptn+kF+BT7oTEY9OEqA71EVz2z3q6nzYHXFhp+L6w5GUkNKKjophXQ/bCMrHgp6UJfDK8C0ny7zLL56TgutRi1Kp64LKlfzCws+jGr0LakEMoqm+JLgFXDz2KVfdxGFkH7/P7d88NfIxA+Jb7EAoujGMWxaUydeY7BX9kD24u6o3FQiXkBLs3E7ZFi4YzG3uMVr7ZXh3h1EJfJEGd/z2cSch8MYe2JRWA56mtDvR7g23CRC99tiD062MPvCrAE8HRD1JaDvLotnt1Q7ODN4fm+nJhhQdFQRwPnM0vweWHTg02dB+57JC+DpoVcxTgU462cPRh5jAaXObiDPp06jY05nDXXdS9fB/pOSNf0s5+lIsVaDkVfNvCAQs48P7So2OpZM5dT1E9ziGdcQObemBbdMBi8iwIYHo9lbciLmB24MEQKa2ormpYrOKk3T1TSuGydfF/hdQQGTC1gGA5iv/wvgEghtzZzYICoJ8j7G0zHor/do6cuILmn8yYUo4yAa5wBdQUWeIyh5dpwYWpU72Nn/CxQYtA+msYTM+i142tKVjR2xyELD6KEXjsv7D
log4j.logger.davmail=INFO
davmail.ssl.clientKeystoreType=
davmail.clientSoTimeout=
davmail.ssl.pkcs11Config=
davmail.ssl.clientKeystorePass=
davmail.imapPort=1143
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx
log4j.logger.org.apache.http.conn.ssl=INFO
davmail.sentKeepDelay=90
davmail.ssl.nosecureldap=false
davmail.imapAlwaysApproxMsgSize=false
davmail.ssl.nosecurecaldav=false
davmail.popPort=1110
davmail.defaultDomain=
davmail.showStartupBanner=true
davmail.proxyHost=
davmail.ldapPort=1389
davmail.server.certificate.hash=
log4j.logger.org.apache.http.wire=INFO
davmail.disableGuiNotifications=false
davmail.imapIdleDelay=
davmail.allowRemote=false
davmail.disableUpdateCheck=true
log4j.logger.org.apache.http=INFO
davmail.caldavPort=1080
davmail.enableKeepAlive=true
davmail.ssl.clientKeystoreFile=
davmail.logFilePath=/home/jds6696/.davmail.log
davmail.keepDelay=30
davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob
davmail.caldavAlarmSound=
